import { ComponentType } from '../../types/UIConfiguration.types';
import { BUTTON_W_CTA } from 'components/uiBuilder/BUTTON/BUTTON_W_CTA/BUTTON_W_CTA';
import { CAROUSEL_LANDSCAPE_W_BG } from 'components/uiBuilder/CAROUSEL/CAROUSEL_LANDSCAPE_W_BG/CAROUSEL_LANDSCAPE_W_BG';
import { CAROUSEL_LANDSCAPE_W_BODY_CTA } from 'components/uiBuilder/CAROUSEL/CAROUSEL_LANDSCAPE_W_BODY_CTA/CAROUSEL_LANDSCAPE_W_BODY_CTA';
import { CAROUSEL_LARGE_IMG_W_BG } from 'components/uiBuilder/CAROUSEL/CAROUSEL_LARGE_IMG_W_BG/CAROUSEL_LARGE_IMG_W_BG';
import { CAROUSEL_PORTRAIT_W_BG } from 'components/uiBuilder/CAROUSEL/CAROUSEL_PORTRAIT_W_BG/CAROUSEL_PORTRAIT_W_BG';
import { CAROUSEL_SOCIAL } from 'components/uiBuilder/CAROUSEL/CAROUSEL_SOCIAL/CAROUSEL_SOCIAL';
import { CAROUSEL_WO_BG } from 'components/uiBuilder/CAROUSEL/CAROUSEL_WO_BG/CAROUSEL_WO_BG';
import { HERO_BANNER_W_CTA } from 'components/uiBuilder/HERO_BANNER/HERO_BANNER_W_CTA/HERO_BANNER_W_CTA';
import { HERO_BANNER_W_SUBTITLE_CTA } from 'components/uiBuilder/HERO_BANNER/HERO_BANNER_W_SUBTITLE_CTA/HERO_BANNER_W_SUBTITLE_CTA';
import { HERO_BANNER_W_TITLE } from 'components/uiBuilder/HERO_BANNER/HERO_BANNER_W_TITLE/HERO_BANNER_W_TITLE';
import { SMALL_BANNER_W_TITLE } from 'components/uiBuilder/HERO_BANNER/SMALL_BANNER_W_TITLE/SMALL_BANNER_W_TITLE';
import { IMAGE_LARGE } from 'components/uiBuilder/IMAGE/IMAGE_LARGE/IMAGE_LARGE';
import { IMAGE_LARGE_W_TITLE_BODY } from 'components/uiBuilder/IMAGE/IMAGE_LARGE_W_TITLE_BODY/IMAGE_LARGE_W_TITLE_BODY';
import { IMAGE_LARGE_W_TITLE_SUBTITLE_BODY } from 'components/uiBuilder/IMAGE/IMAGE_LARGE_W_TITLE_SUBTITLE_BODY/IMAGE_LARGE_W_TITLE_SUBTITLE_BODY';
import { IMAGE_W_TITLE_BODY } from 'components/uiBuilder/IMAGE/IMAGE_W_TITLE_BODY/IMAGE_W_TITLE_BODY';
import { IMAGE_LARGE_W_BG } from 'components/uiBuilder/IMAGE/IMAGE_LARGE_W_BG/IMAGE_LARGE_W_BG';
import { SERVICE_DETAIL_COMPONENT } from 'components/uiBuilder/IMAGE/SERVICE_DETAIL_COMPONENT/SERVICE_DETAIL_COMPONENT';
import { ACCORDION_W_ICON } from 'components/uiBuilder/ACCORDION/ACCORDION_W_ICON/ACCORDION_W_ICON';
import { ACCORDION_WO_ICON } from 'components/uiBuilder/ACCORDION/ACCORDION_WO_ICON/ACCORDION_WO_ICON';
import { LIST_COMPONENT } from 'components/uiBuilder/ELEVATE_COMPONENTS/LIST_COMPONENT/LIST_COMPONENT';
import { DETAIL_PAGE } from 'components/uiBuilder/ELEVATE_COMPONENTS/DETAIL_PAGE/DETAIL_PAGE';

export const componentsMap = {
  // Hero banner
  [ComponentType.HERO_BANNER_W_CTA]: HERO_BANNER_W_CTA,
  [ComponentType.HERO_BANNER_W_TITLE]: HERO_BANNER_W_TITLE,
  [ComponentType.HERO_BANNER_W_SUBTITLE_CTA]: HERO_BANNER_W_SUBTITLE_CTA,
  [ComponentType.SMALL_BANNER_W_TITLE]: SMALL_BANNER_W_TITLE,
  [ComponentType.CAROUSEL_LANDSCAPE_W_BG]: CAROUSEL_LANDSCAPE_W_BG,
  [ComponentType.CAROUSEL_LANDSCAPE_W_BODY_CTA]: CAROUSEL_LANDSCAPE_W_BODY_CTA,
  [ComponentType.CAROUSEL_LARGE_IMG_W_BG]: CAROUSEL_LARGE_IMG_W_BG,
  [ComponentType.CAROUSEL_PORTRAIT_W_BG]: CAROUSEL_PORTRAIT_W_BG,
  [ComponentType.CAROUSEL_SOCIAL]: CAROUSEL_SOCIAL,
  [ComponentType.CAROUSEL_WO_BG]: CAROUSEL_WO_BG,
  [ComponentType.BUTTON_W_CTA]: BUTTON_W_CTA,
  [ComponentType.IMAGE_LARGE]: IMAGE_LARGE,
  [ComponentType.IMAGE_LARGE_W_BG]: IMAGE_LARGE_W_BG,
  [ComponentType.IMAGE_LARGE_W_TITLE_BODY]: IMAGE_LARGE_W_TITLE_BODY,
  [ComponentType.IMAGE_LARGE_W_TITLE_SUBTITLE_BODY]: IMAGE_LARGE_W_TITLE_SUBTITLE_BODY,
  [ComponentType.IMAGE_W_TITLE_BODY]: IMAGE_W_TITLE_BODY,
  [ComponentType.SERVICE_DETAIL_COMPONENT]: SERVICE_DETAIL_COMPONENT,
  [ComponentType.ACCORDION_W_ICON]: ACCORDION_W_ICON,
  [ComponentType.ACCORDION_WO_ICON]: ACCORDION_WO_ICON,
  [ComponentType.LIST_COMPONENT]: LIST_COMPONENT,
  [ComponentType.DETAIL_PAGE]: DETAIL_PAGE,
};
