# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:18.12.1
pipelines:
  #default:
  #  - step:
  #      name: Build and test
  #      script:
  #        - rm -rf package-lock.json
  #        - rm -rf yarn.lock
  #        - rm -rf node_modules
  #        - yarn
  branches: # Pipelines that run automatically on a push to a master
    master:
      - step:
          deployment: uat
          size : 2x
          caches:
            - node
          name: Automatacilly Deploy to Infinite Dev https://pwa-infinite-dev.hudini.app/
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:sofitel
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_PWA_INFINITE_DEV
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E9PVO4YEDANZA'         
  custom:
    deployToSofitelStaging:
      - step:
          caches:
            - node
          name: Deploy Manually to Staging https://sofitel.hudinielevate-stage.io/
          deployment: staging
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:stage
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_STAGING # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_STAGING # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_STAGING # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_SOFITEL_STAGE
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_STAGING
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_STAGING
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_STAGING
                DISTRIBUTION_ID: 'EU8Z583GKAK65'
    deployToSofitelUAT:
      - step:
          caches:
            - node
          name: Deploy Manually to UAT https://sofitel.hudini.app/
          deployment: uat
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:sofitel
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_SOFITEL_UAT
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E3DU5R0R1H7FSF'
    deployToFairmontUAT:
      - step:
          caches:
            - node
          name: Deploy Manually to UAT https://fairmont.hudini.app/
          deployment: uat
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:fairmont
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_FAIRMONT_UAT
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E2UKK3TQ2VVU2N'
    deployToRafflesUAT:
      - step:
          caches:
            - node
          name: Deploy Manually to UAT https://raffles.hudini.app/
          deployment: uat
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:raffles
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_RAFFLES_UAT
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E3PFBGDNMD6JBU'
    deployToITCUAT:
      - step:
          caches:
            - node
          name: Deploy Manually to UAT https://itc.hudini.app/
          deployment: uat
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:itc
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_ITC_UAT
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E3QW2SJVKM9B2L'
    deployToAtlantisUAT:
      - step:
          caches:
            - node
          name: Deploy Manually to UAT https://atlantis-pwa.hudini.app/
          deployment: uat
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:atlantis
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_ATLANTIS_UAT
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E3ZUF2S563M5Q'
    deployToInfiniteQA:
      - step:
          caches:
            - node
          name: Deploy Manually to UAT(QA) https://pwa-infinite-qa.hudini.app/
          deployment: uat
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:sofitel
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_PWA_INFINITE_STAGE
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E3QOETK7ZFR0UR' 
    deployToInfiniteUAT:
      - step:
          caches:
            - node
          name: Deploy Manually to UAT https://pwa-infinite.hudini.app/
          deployment: uat
          size: 2x # Double resources available for this step.
          script:
            - rm -rf package-lock.json
            - rm -rf yarn.lock
            - rm -rf node_modules
            - yarn
            - CI='' yarn build:sofitel
            - CI='' yarn export
            - cd out
            - pipe: atlassian/aws-s3-deploy:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT # Optional if already defined in the context.
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT # Optional if already defined in the context.
                #ACL: 'public-read'
                S3_BUCKET: $S3_BUCKET_PWA_INFINITE_UAT
                LOCAL_PATH: $(pwd)
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_UAT
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_UAT
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_UAT
                DISTRIBUTION_ID: 'E2IJ27PQ9E08IU'
