import { Countries } from 'utils/countryList';

export const configuration = [
  {
    code: 'pwa-demo',
    name: 'PWA Demo',
    hotelId: '78402815-a21e-486f-992b-91104e0cb887',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Aadhaar Card',
                        value: 'Aadhaar Card',
                        code: 'ID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Driving License',
                        value: 'Driving License',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              // {
              //   name: 'expiryDate',
              //   label: 'Document Expiry',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              //   isDisableFuture: true,
              //   isDisablePast: true,
              // },
              // {
              //   name: 'countryOfIssue',
              //   label: 'Document Issuing Authority',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              // },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              // {
              //   name: 'issueCountry',
              //   cmsName: 'COUNTRY_OF_ISSUE',
              //   label: 'Document Issuing Authority',
              // },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    code: 'sofitel-manila',
    name: 'Sofitel Manila',
    hotelId: '259034ee-3f5c-43b0-9332-dffd85ccba65',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Identity Card',
                        value: 'IDC',
                        code: 'IDC',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Drivers License',
                        value: 'DRL',
                        code: 'DRL',
                        youverse: 'DRIVING_LICENSE',
                      },
                      {
                        name: 'Resident Card',
                        value: 'RES',
                        code: 'RES',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Green Card',
                        value: 'GRN',
                        code: 'GRN',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Military ID',
                        value: 'MID',
                        code: 'MID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Social Security Card',
                        value: 'SSC',
                        code: 'SSC',
                        youverse: 'IDENTITY_CARD',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'CYBERSOURCE',
                paymentMethod: 'KIOSK',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'email',
                label: 'Email',
                type: 'email',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              // {
              //   name: 'expiryDate',
              //   label: 'Document Expiry',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              //   isDisableFuture: true,
              //   isDisablePast: true,
              // },
              // {
              //   name: 'countryOfIssue',
              //   label: 'Document Issuing Authority',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              // },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              // {
              //   name: 'issueCountry',
              //   cmsName: 'COUNTRY_OF_ISSUE',
              //   label: 'Document Issuing Authority',
              // },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
      },
    ],
  },
  {
    code: 'itc-grand-chola',
    name: 'ITC Grand Chola',
    hotelId: 'ad0fd522-5f0e-4d2c-9f51-c3a43f546a7a',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'youverse',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Aadhaar Card',
                        value: 'Aadhaar Card',
                        code: 'ID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Driving License',
                        value: 'Driving License',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: true,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'youverse',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'email',
                label: 'Email',
                type: 'email',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              // {
              //   name: 'expiryDate',
              //   label: 'Document Expiry',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              //   isDisableFuture: true,
              //   isDisablePast: true,
              // },
              // {
              //   name: 'countryOfIssue',
              //   label: 'Document Issuing Authority',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              // },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.itchotels.com/in/en/terms' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.itchotels.com/in/en/terms' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              {
                name: 'issueCountry',
                cmsName: 'COUNTRY_OF_ISSUE',
                label: 'Document Issuing Authority',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
      },
    ],
  },
  {
    code: 'raffles-the-palm',
    name: 'Raffles The Palm',
    // demo instance
    hotelId: '78402815-a21e-486f-992b-91104e0cb887',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                      { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                      { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Identity Verification',
                type: 'manual',
                isActive: true,
                details: [
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                      { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                      { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                    ],
                  },

                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'email',
                label: 'Email',
                type: 'email',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
                options: [
                  { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                  { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                  { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                ],
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              // {
              //   name: 'expiryDate',
              //   label: 'Document Expiry',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              //   isDisableFuture: true,
              //   isDisablePast: true,
              // },
              // {
              //   name: 'countryOfIssue',
              //   label: 'Document Issuing Authority',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              // },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              // {
              //   name: 'issueCountry',
              //   cmsName: 'COUNTRY_OF_ISSUE',
              //   label: 'Document Issuing Authority',
              // },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
      },
    ],
  },
  {
    code: 'fairmont-marrakech',
    name: 'Fairmont Marrakech',
    hotelId: 'cadcb011-3655-47c8-a016-e79bb59b5d1e',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'youverse',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                    options: [
                      { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                      { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                      { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                  // {
                  //   name: 'countryOfIssue',
                  //   label: 'Document Issuing Authority',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: false,
                  //   isActive: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Identity Verification',
                type: 'youverse',
                isActive: false,
                details: [
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                      { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                      { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                    ],
                  },

                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'youverse',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'email',
                label: 'Email',
                type: 'email',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
                options: [
                  { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                  { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                  { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                ],
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              // {
              //   name: 'expiryDate',
              //   label: 'Document Expiry',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              //   isDisableFuture: true,
              //   isDisablePast: true,
              // },
              // {
              //   name: 'countryOfIssue',
              //   label: 'Document Issuing Authority',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              // },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.itchotels.com/in/en/terms' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.itchotels.com/in/en/terms' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
      },
    ],
  },
  {
    code: 'atlantis',
    name: 'Atlantis',
    // demo instance
    hotelId: '78402815-a21e-486f-992b-91104e0cb887',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'incode',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                      { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                      { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Identity Verification',
                type: 'manual',
                isActive: true,
                details: [
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                      { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                      { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                    ],
                  },

                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'email',
                label: 'Email',
                type: 'email',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
                options: [
                  { name: 'Passport', value: 'PASSPORT', code: 'PASSPORT' },
                  { name: 'Aadhaar Card', value: 'ID', code: 'IDENTITY_CARD' },
                  { name: 'Driving Licence', value: 'DL', code: 'DRIVING_LICENSE' },
                ],
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              // {
              //   name: 'expiryDate',
              //   label: 'Document Expiry',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              //   isDisableFuture: true,
              //   isDisablePast: true,
              // },
              // {
              //   name: 'countryOfIssue',
              //   label: 'Document Issuing Authority',
              //   type: 'Text',
              //   required: true,
              //   isDisabled: true,
              //   isActive: true,
              // },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              // {
              //   name: 'issueCountry',
              //   cmsName: 'COUNTRY_OF_ISSUE',
              //   label: 'Document Issuing Authority',
              // },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
      },
    ],
  },
];
