import { Countries } from 'utils/countryList';

export const configuration = [
  {
    code: 'stage',
    logo: '',
    name: 'Stage',
    hotelId: '989814e5-2fda-4ab8-b795-33f4d76f1866',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'Confirm Check-In',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Payment Information',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              // {
              //   name: 'issueCountry',
              //   cmsName: 'COUNTRY_OF_ISSUE',
              //   label: 'Document Issuing Authority',
              // },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'uat',
    logo: '',
    name: 'UAT',
    hotelId: '78402815-a21e-486f-992b-91104e0cb887',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'Confirm Check-In',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'sofitel-manila',
    logo: '',
    name: 'Sofitel Manila',
    hotelId: '259034ee-3f5c-43b0-9332-dffd85ccba65',
    pms: 'OPERA',
    fetchFromDb: 'no',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    isLogoLoaderActive: false,
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Identity Card',
                        value: 'IDC',
                        code: 'IDC',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Drivers License',
                        value: 'DRL',
                        code: 'DRL',
                        youverse: 'DRIVING_LICENSE',
                      },
                      {
                        name: 'Resident Card',
                        value: 'RES',
                        code: 'RES',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Green Card',
                        value: 'GRN',
                        code: 'GRN',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Military ID',
                        value: 'MID',
                        code: 'MID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Social Security Card',
                        value: 'SSC',
                        code: 'SSC',
                        youverse: 'IDENTITY_CARD',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'NONE',
                paymentMethod: 'KIOSK',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'Confirm Check-In',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Payment Information',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: false,
        type: 'vendor',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'itc-grand-chola',
    logo: '',
    name: 'ITC Grand Chola',
    hotelId: 'ad0fd522-5f0e-4d2c-9f51-c3a43f546a7a',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    preCheckInOnly: true,
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'youverse',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Aadhaar Card',
                        value: 'ID',
                        code: 'ID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'CCAVENUE',
                details: [
                  {
                    name: 'paymentType',
                    label: 'Payment Method',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'youverse',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'Confirm Check-In',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Payment Information',
              details: [
                {
                  name: 'paymentType',
                  label: 'Payment Method',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              {
                name: 'issueCountry',
                cmsName: 'COUNTRY_OF_ISSUE',
                label: 'Document Issuing Authority',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: false,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: false,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: false,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: false,
      },
    ],
  },
  {
    code: 'itc-welcomhotel-chennai',
    name: 'ITC WelcomHotel Chennai',
    hotelId: 'd9a0e344-a5aa-4186-8095-49200ea7bbbe',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    preCheckInOnly: true,
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'youverse',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Aadhaar Card',
                        value: 'PSUC',
                        code: 'PSUC',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Driving License',
                        value: 'DRIV',
                        code: 'DRIV',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                isTotalChargeActive: true,
                type: 'CCAVENUE',
                details: [
                  {
                    name: 'paymentType',
                    label: 'Payment Method',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'youverse',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'Confirm Check-In',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Payment Information',
              details: [
                {
                  name: 'paymentType',
                  label: 'Payment Method',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              {
                name: 'issueCountry',
                cmsName: 'COUNTRY_OF_ISSUE',
                label: 'Document Issuing Authority',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: false,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: false,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: false,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: false,
      },
    ],
  },
  {
    code: 'raffles-the-palm-dubai',
    logo: '',
    name: 'Raffles The Palm Dubai',
    hotelId: '4e67ef89-b1d7-42fd-9cf0-70001cae54fc',
    pms: 'OPERA',
    fetchFromDb: 'no',
    saveToDb: 'yes',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    isAnimationActive: false,
    isLogoLoaderActive: false,
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: false,
      },
      {
        code: 'Pair-To-Room',
        name: 'Pair to Room',
        isActive: true,
        welcomeTitle: 'Welcome to Raffles The Palm',
        welcomeBody:
          // eslint-disable-next-line quotes
          "Welcome to Raffles The Palm - the only Palace of its kind, blending timeless craftmanship with Dubai's vibrant social culture in an ultra-luxury beach resort environment.",
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'VENDOR',
        payment: [{ id: '1', name: 'BILL TO ROOM', message: '' }],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'VENDOR',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: false,
      },
    ],
  },
  {
    code: 'fairmont-royal-palm-marrakech',
    logo: 'royal palm marrakech',
    name: 'Fairmont Royal Palm Marrakech',
    hotelId: 'cadcb011-3655-47c8-a016-e79bb59b5d1e',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'PAS',
                        code: 'PAS',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DRL',
                        code: 'DRL',
                        youverse: 'DRIVING_LICENSE',
                      },
                      {
                        name: 'ID',
                        value: 'ID',
                        code: 'ID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Military ID',
                        value: 'MID',
                        code: 'MID',
                        youverse: 'IDENTITY_CARD',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'NONE',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'youverse',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'Confirm Check-In',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Payment Information',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'Pair-To-Room',
        name: 'Pair to Room',
        isActive: true,
        welcomeTitle: 'Welcome to Fairmont Royal Palm Marrakech',
        welcomeBody:
          'Backed by the snowy peaks of the Atlas Mountains and wrapped in landscaped water gardens, Fairmont Marrakech Royal Palm is a luxury Marrakech hotel welcoming business and leisure travelers alike',
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'VENDOR',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'VENDOR',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'fairmont-the-palm-dubai',
    logo: 'the palm',
    name: 'Fairmont The Palm Dubai',
    hotelId: 'dc9849bf-bef7-4ba9-a288-cea18f493173',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: false,
      },
      {
        code: 'Pair-To-Room',
        name: 'Pair to Room',
        isActive: true,
        welcomeTitle: 'Welcome to Fairmont The Palm',
        welcomeBody:
          // eslint-disable-next-line quotes
          "Escape to Dubai's Fairmont The Palm, an Arabian-style sanctuary that combines heartfelt hospitality with elegant sophistication.",
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [{ id: '1', name: 'BILL TO ROOM', message: '' }],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: '1-hotel-south-beach',
    logo: '',
    name: '1 Hotel South Beach',
    hotelId: '003a8b2c-3c06-4afd-9b44-c8ecf66395a4',
    pms: 'INFOR',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'FREEDOMPAY',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: false,
        type: 'VENDOR',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'VENDOR',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'proper-downtown-la',
    name: 'Proper Downtown L.A.',
    hotelId: 'af33df72-467c-40f9-b2d3-ac9d56a7fb85',
    pms: 'INFOR',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'Confirm Check-In',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Payment Information',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'VENDOR',
        payment: [{ id: '1', name: 'BILL TO ROOM', message: '' }],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'VENDOR',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'atlantis',
    logo: '',
    name: 'Atlantis',
    // demo instance
    hotelId: '78402815-a21e-486f-992b-91104e0cb887',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    orderOfModules: [
      'hotel-info',
      'check-in',
      'offers',
      'services',
      'dining',
      'spa',
      'hotel-compendium',
    ],
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'incode',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition:
              'I have read, understood and agree to the Terms & Conditions and Privacy Laws.',
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Payment Information',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
];
