import { Countries } from 'utils/countryList';

export const configuration = [
  {
    code: 'stage',
    name: 'Stage',
    hotelId: '989814e5-2fda-4ab8-b795-33f4d76f1866',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  // {
                  //   name: 'expiryDate',
                  //   label: 'Document Expiry',
                  //   type: 'Text',
                  //   required: true,
                  //   isDisabled: true,
                  //   isActive: true,
                  //   isDisableFuture: true,
                  //   isDisablePast: true,
                  // },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              // {
              //   name: 'issueCountry',
              //   cmsName: 'COUNTRY_OF_ISSUE',
              //   label: 'Document Issuing Authority',
              // },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'uat',
    name: 'UAT',
    hotelId: '78402815-a21e-486f-992b-91104e0cb887',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'sofitel-manila',
    name: 'Sofitel Manila',
    hotelId: '259034ee-3f5c-43b0-9332-dffd85ccba65',
    pms: 'OPERA',
    fetchFromDb: 'no',
    saveToDb: 'no',
    isLogoLoaderActive: false,
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Identity Card',
                        value: 'IDC',
                        code: 'IDC',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Drivers License',
                        value: 'DRL',
                        code: 'DRL',
                        youverse: 'DRIVING_LICENSE',
                      },
                      {
                        name: 'Resident Card',
                        value: 'RES',
                        code: 'RES',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Green Card',
                        value: 'GRN',
                        code: 'GRN',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Military ID',
                        value: 'MID',
                        code: 'MID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Social Security Card',
                        value: 'SSC',
                        code: 'SSC',
                        youverse: 'IDENTITY_CARD',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'NONE',
                paymentMethod: 'KIOSK',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: false,
        type: 'vendor',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'itc-grand-chola',
    name: 'ITC Grand Chola',
    hotelId: 'ad0fd522-5f0e-4d2c-9f51-c3a43f546a7a',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'youverse',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Aadhaar Card',
                        value: 'ID',
                        code: 'ID',
                        youverse: 'IDENTITY_CARD',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'youverse',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.itchotels.com/in/en/terms' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.itchotels.com/in/en/terms' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
              {
                name: 'issueCountry',
                cmsName: 'COUNTRY_OF_ISSUE',
                label: 'Document Issuing Authority',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',

        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'raffles-the-palm-dubai',
    logo: 'the palm dubai',
    name: 'Raffles The Palm Dubai',
    hotelId: '4e67ef89-b1d7-42fd-9cf0-70001cae54fc',
    pms: 'OPERA',
    fetchFromDb: 'no',
    saveToDb: 'yes',
    isAnimationActive: false,
    isLogoLoaderActive: false,
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: false,
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'VENDOR',
        payment: [{ id: '1', name: 'BILL TO ROOM', message: '' }],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'VENDOR',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: false,
      },
    ],
  },
  {
    code: 'fairmont-royal-palm-marrakech',
    name: 'Fairmont Royal Palm Marrakech',
    hotelId: 'cadcb011-3655-47c8-a016-e79bb59b5d1e',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'youverse',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'youverse',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },

              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.fairmont.com/terms-and-conditions/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://all.accor.com/information/legal/data-protection.en.shtml?merchantid=MS-MULTI-FAIRMONT&sourceid=UTM_gclid&gacid=807341428.1704366251&otConsentId=f6a0c919-fe6f-465c-aceb-1ddd1dab6a8f&otConsentString=,C0001,C0003,C0007,C0002,C0004,&partner_id=fairmont&_ga=2.13984114.474450766.1704366252-807341428.1704366251&_gac=1.127310591.1704366252.Cj0KCQiAy9msBhD0ARIsANbk0A9D1XlscxGHpwAkDa6mJT2sBaFCZ4ibkRuePtHHQ6EkhERDZ_mBDp8aAj1GEALw_wcB&_gl=1*j9eppi*_ga*ODA3MzQxNDI4LjE3MDQzNjYyNTE.*_ga_WPLEEQEV59*MTcwNDM2NjI1MS4xLjEuMTcwNDM2NjMwMC4wLjAuMA..*_fplc*N3dGYm95ajc1OUhaeFo5emoyNllscDBIaUpENHc5RkhHdHJuWDF4UGpjZHAyNlZDR3NnTlFGJTJGWjQ3WnQ4TWV0MCUyQmhZemFJeVVpRXowbkZlNnloT05TN0VXNm54YjdQYkNaJTJCRkVnY2pUSGNEVkxHWlV0VTFBZlplaTRTelZBJTNEJTNE' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'fairmont-the-palm-dubai',
    name: 'Fairmont The Palm Dubai',
    hotelId: 'dc9849bf-bef7-4ba9-a288-cea18f493173',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'NONE',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: ' CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.fairmont.com/terms-and-conditions/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://all.accor.com/information/legal/data-protection.en.shtml?merchantid=MS-MULTI-FAIRMONT&sourceid=UTM_gclid&gacid=807341428.1704366251&otConsentId=f6a0c919-fe6f-465c-aceb-1ddd1dab6a8f&otConsentString=,C0001,C0003,C0007,C0002,C0004,&partner_id=fairmont&_ga=2.13984114.474450766.1704366252-807341428.1704366251&_gac=1.127310591.1704366252.Cj0KCQiAy9msBhD0ARIsANbk0A9D1XlscxGHpwAkDa6mJT2sBaFCZ4ibkRuePtHHQ6EkhERDZ_mBDp8aAj1GEALw_wcB&_gl=1*j9eppi*_ga*ODA3MzQxNDI4LjE3MDQzNjYyNTE.*_ga_WPLEEQEV59*MTcwNDM2NjI1MS4xLjEuMTcwNDM2NjMwMC4wLjAuMA..*_fplc*N3dGYm95ajc1OUhaeFo5emoyNllscDBIaUpENHc5RkhHdHJuWDF4UGpjZHAyNlZDR3NnTlFGJTJGWjQ3WnQ4TWV0MCUyQmhZemFJeVVpRXowbkZlNnloT05TN0VXNm54YjdQYkNaJTJCRkVnY2pUSGNEVkxHWlV0VTFBZlplaTRTelZBJTNEJTNE' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: '1-hotel-south-beach',
    name: '1 Hotel South Beach',
    hotelId: '003a8b2c-3c06-4afd-9b44-c8ecf66395a4',
    pms: 'INFOR',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'manual',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'Tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'FREEDOMPAY',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'Tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.1hotels.com/terms-conditions' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.1hotels.com/privacy-policy' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
  {
    code: 'atlantis',
    name: 'Atlantis',
    // demo instance
    hotelId: '78402815-a21e-486f-992b-91104e0cb887',
    pms: 'OPERA',
    fetchFromDb: 'yes',
    saveToDb: 'no',
    modules: [
      {
        code: 'Preferences',
        name: 'Preferences',
        isActive: true,
        submodules: [
          {
            code: 'Headers',
            isActive: true,
            details: [
              {
                title: 'ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW',
              },
            ],
          },
        ],
      },
      {
        code: 'Check-In',
        name: 'Check-In',
        isActive: true,
        submodules: [
          {
            name: 'information',
            label: 'Check-In',
            title: 'Please Complete Your Check-In Process',
            isActive: true,
            details: [
              {
                name: 'Guest Information',
                isActive: true,
                type: 'incode',
                details: [
                  {
                    name: 'firstName',
                    label: 'First Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'lastName',
                    label: 'Last Name',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'emails',
                    label: 'Email',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'phone',
                    label: 'Phone Number',
                    type: 'tel',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'countryCode',
                    label: 'Country',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: Countries,
                  },
                  {
                    name: 'docType',
                    label: 'Document Type',
                    type: 'Select',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                    options: [
                      {
                        name: 'Passport',
                        value: 'Passport',
                        code: 'PASSPORT',
                        youverse: 'PASSPORT',
                      },
                      {
                        name: 'Driving License',
                        value: 'DL',
                        code: 'DL',
                        youverse: 'DRIVING_LICENSE',
                      },
                    ],
                  },
                  {
                    name: 'docNo',
                    label: 'Document Number',
                    type: 'Text',
                    required: true,
                    isDisabled: false,
                    isActive: true,
                  },
                  {
                    name: 'issueCountry',
                    label: 'Document Issuing Authority',
                    type: 'text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                ],
              },
              {
                name: 'Credit Card Info',
                isActive: true,
                type: 'SHIFT4',
                details: [
                  {
                    name: 'cardNumber',
                    label: 'Card Number',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardHolderName',
                    label: 'Card Holder Name',
                    type: 'Text',
                    required: false,
                    isDisabled: true,
                    isActive: false,
                  },
                  {
                    name: 'cardType',
                    label: 'Card Type',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                  {
                    name: 'cardExpiryDate',
                    label: 'Expiry Date',
                    type: 'Text',
                    required: true,
                    isDisabled: true,
                    isActive: true,
                  },
                ],
              },
            ],
          },
          {
            name: 'accompanyingGuest',
            label: 'Secondary Guest',
            title: '',
            type: 'manual',
            isActive: true,
            cardIcon: 'guest',
            details: [
              {
                name: 'firstName',
                label: 'First Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'lastName',
                label: 'Last Name',
                type: 'Text',
                required: true,
                isDisabled: true,
                isActive: true,
              },
              {
                name: 'emails',
                label: 'Email',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'phone',
                label: 'Phone Number',
                type: 'tel',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docType',
                label: 'Document Type',
                type: 'Select',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'docNo',
                label: 'Document Number',
                type: 'Text',
                required: true,
                isDisabled: false,
                isActive: true,
              },
              {
                name: 'condition',
                label:
                  'I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.',
                type: 'CheckBox',
                required: true,
                isDisabled: false,
                isActive: false,
              },
            ],
          },
          {
            name: 'personalisation',
            label: 'Customize My Stay',
            title: 'Check-In',
            type: 'cms',
            isActive: true,
          },
          {
            name: 'review',
            label: 'Review & Sign',
            title: 'Check-In',
            buttonLabelCheckIn: 'CONFIRM CHECK-IN',
            // eslint-disable-next-line quotes
            termsAndCondition: `I have read, understood and agree to the <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Terms & Conditions</a> and <a href='https://www.sofitelmanila.com/privacy-policy/' target='_blank' rel='noopener noreferrer'>Privacy Laws</a>.`,
            subTitle:
              'Please review and confirm the below information to complete the Check-In process',
            type: 'cms',
            isActive: true,
            guestInformationDetails: [
              {
                title: 'Guest Information',
              },
              {
                checkIn: 'Check-In',
                checkOut: 'Checkout',
              },
            ],
            creditCardDetails: {
              title: 'Credit Card Info',
              details: [
                {
                  name: 'cardNumber',
                  label: 'Card Number',
                },
                {
                  name: 'cardType',
                  label: 'Card Type',
                },
                {
                  name: 'cardExpiryDate',
                  label: 'Expiry Date',
                },
              ],
            },
            identityVerificationDetails: [
              {
                title: 'Identity Verification',
              },
              {
                name: 'docType',
                cmsName: 'DOCUMENT_TYPE',
                label: 'Document Type',
              },
              {
                name: 'docNo',
                cmsName: 'DOCUMENT_NUMBER',
                label: 'Document Number',
              },
            ],
            personalizationDetails: [
              {
                title: 'Add-Ons',
              },
            ],
          },
        ],
      },
      {
        code: 'In-Room Dining',
        name: 'In-Room Dining',
        isActive: true,
        type: 'CMS',
        payment: [
          { id: '1', name: 'BILL TO ROOM', message: '' },
          { id: '2', name: 'CASH', message: '' },
          { id: '3', name: 'CARD', message: '' },
        ],
      },
      {
        code: 'Services',
        name: 'Services',
        isActive: true,
        type: 'CMS',
      },
      {
        code: 'view-bill',
        name: 'View Bill',
        isActive: true,
      },
      {
        code: 'checkout',
        name: 'Checkout',
        isActive: true,
      },
    ],
  },
];
